# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatViewMVVMSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChatViewMVVMSample
  pod 'SnapKit', '~> 5.0.0'
  pod 'Then'
  pod 'Kingfisher', '~> 7.0'

  target 'ChatViewMVVMSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChatViewMVVMSampleUITests' do
    # Pods for testing
  end

end
